import * as Js1 from "./gestionPresupuesto.js";
import * as Js2 from "./gestionPresupuestoWeb.js";
Js1.actualizarPresupuesto(1500);
Js2.mostrarDatoenId(Js1.mostrarPresupuesto(), "presupuesto");
let gasto1 = new Js1.CrearGasto("Compra carne", 23.44, "2021-10-06", "casa", "comida");
let gasto2 = new Js1.CrearGasto("Compra fruta y verdura", 14.25, "2021-09-06", "supermercado", "comida");
let gasto3 = new Js1.CrearGasto("Bonobús", 18.60, "2020-05-26", "transporte");
let gasto4 = new Js1.CrearGasto("Gasolina", 60.42, "2021-10-08", "transporte", "gasolina");
let gasto5 = new Js1.CrearGasto("Seguro hogar", 206.45, "2021-09-26", "casa", "seguros");
let gasto6 = new Js1.CrearGasto("Seguro coche", 195.78, "2021-10-06", "transporte", "seguros");
Js1.anyadirGasto(gasto1);
Js1.anyadirGasto(gasto2);
Js1.anyadirGasto(gasto3);
Js1.anyadirGasto(gasto4);
Js1.anyadirGasto(gasto5);
Js1.anyadirGasto(gasto6);
Js2.mostrarDatoenId(Js1.calcularTotalGastos(), "gastos-totales");
Js2.mostrarDatoenId(Js1.calcularBalance(), "balance-total");
Js2.mostrarGastoWeb(Js1.listarGastos(), "listado-gastos-completo");
Js2.mostrarGastoWeb(Js1.filtrarGastos({fechaDesde : "2021-09-01", fechaHasta : "2021-09-30"}), "listado-gastos-filtrado-1");
Js2.mostrarGastoWeb(Js1.filtrarGastos({valorMinimo : "50"}), "listado-gastos-filtrado-2");
Js2.mostrarGastoWeb(Js1.filtrarGastos({valorMinimo : "200", etiquetasTiene : ["seguros"]}), "listado-gastos-filtrado-3");
Js2.mostrarGastoWeb(Js1.filtrarGastos({valorMaximo : "50", etiquetasTiene : ["comida", "transporte"]}), "listado-gastos-filtrado-4");

